services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    #secrets:
    #  - server-certificate
    volumes:
      - ./configs/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./logs/mosquitto/log:/mosquitto/log
    network_mode: bridge
  infoscreen:
    image: inuitviking/lpos:0.0.2
    ports:
      - "80:80"
      - "443:443"
    expose: [80,443]
    volumes:
      - ./configs/infoscreen/config:/var/www/config
      - ./configs/infoscreen/apache/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./configs/infoscreen/apache/infoscreen.conf:/etc/httpd/conf.d/infoscreen.conf
      - ./logs/infoscreen/logs:/var/log/httpd
    network_mode: bridge
