services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    #secrets:
    #  - server-certificate
    volumes:
      - ./configs/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./logs/mosquitto/log:/mosquitto/log
    networks:
      - shared
  infoscreen:
    image: 
    ports:
      - "8080:80"
    #secrets:
    # - server-certificate
    volumes:
      - ./configs/infoscreen/config:/var/www/config
      - ./data/infoscreen/data:/var/www/data
      - ./logs/infoscreen/log:/var/www/logs
    networks:
      - shared

networks:
  shared:
    - driver: bridge