services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    #secrets:
    #  - server-certificate
    volumes:
      - ./configs/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./logs/mosquitto/log:/mosquitto/log
    network_mode: bridge
  infoscreen:
    image: inuitviking/lpos:0.0.2
    ports:
      - "80:8080"
    expose: [80]
    volumes:
      - ./configs/infoscreen/config:/var/www/config
      - ./data/infoscreen/data:/var/www/data
      - ./logs/infoscreen/logs:/var/www/logs
    network_mode: bridge
